# Generated by Django 3.2.9 on 2021-11-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('dlnumber', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('dclass', models.CharField(max_length=100)),
                ('rcode', models.CharField(max_length=100)),
                ('ecode', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('edate', models.CharField(max_length=100)),
                ('idate', models.CharField(max_length=100)),
                ('udate', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('eyeclr', models.CharField(max_length=100)),
                ('hairclr', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=7)),
                ('discriminator', models.CharField(max_length=100)),
                ('connum', models.CharField(max_length=100)),
                ('barcode_img', models.FileField(upload_to='')),
            ],
        ),
    ]
