# Generated by Django 3.2.9 on 2021-11-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='county',
        ),
        migrations.AddField(
            model_name='barcode',
            name='country',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
