# Generated by Django 3.2.9 on 2021-11-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211113_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='barcode_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
