# Generated by Django 3.2.9 on 2021-11-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_barcode_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IIN', models.BigIntegerField()),
                ('State', models.CharField(max_length=30)),
                ('Abbreviation', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='country',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='state',
        ),
    ]
