# Generated by Django 3.2.9 on 2021-11-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_barcode_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Abbreviation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='State',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
